### ISSUE TITLE
Error massage when running runner.py populate_with_network_deterministic.txt

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [grid-parity-exchange/Prescient#60]
During the installation, when running runner.py populate_with_network_deterministic.txt I have the following errors. I am attaching the error output file.
[error.txt](https://github.com/grid-parity-exchange/Prescient/files/5591801/error.txt)

Thanks in advance.

**Comment by bknueven** [comment]
@MajidSKhoshghalb it looks like you're using a version of the code that's a month or two old. Prescient is undergoing very active development at the moment -- I recommend updating EGRET and Prescient to the latest version on GitHub.

**Comment by MajidSKhoshghalb** [comment]
Many thanks for your quick reply Bernard.

**Comment by MajidSKhoshghalb** [comment]
I have updated both and just have another error by running runner.py simulate_with_network_deterministic.txt:


Initializing simulation...
ruc_start_hours: [0]
Dates to simulate: ['2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16']

Last RUC date: 2020-07-16
Using current day's forecasts for RUC solves

Initial condition detail (gen-name t0-unit-on t0-unit-on-state t0-power-generated):
Traceback (most recent call last):
  File "C:\Users\anaconda3\Scripts\simulator.py-script.py", line 33, in <module>
    sys.exit(load_entry_point('prescient', 'console_scripts', 'simulator.py')())
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\scripts\simulator.py", line 13, in main
    prescient.simulator.prescient.main(args)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\simulator\prescient.py", line 134, in main
    main_prescient(options)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\simulator\prescient.py", line 77, in main_prescient
    ans = simulator.simulate(options)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\simulator\simulator.py", line 88, in simulate
    oracle_manager.call_initialization_oracle(options, first_time_step)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\simulator\oracle_manager.py", line 124, in call_initialization_oracle
    ruc_plan = self._generate_ruc(options, time_step.hour, time_step.date, None)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\simulator\oracle_manager.py", line 154, in _generate_ruc
    options.run_ruc_with_next_day_data,
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\engine\egret\engine.py", line 81, in create_deterministic_ruc
    report_initial_conditions_for_deterministic_ruc(ruc)
  File "c:\users\desktop\python-test\grid\prescient-master\prescient\engine\egret\reporting.py", line 20, in report_initial_conditions_for_deterministic_ruc
    for g,gdict in tgens.items():
AttributeError: 'generator' object has no attribute 'items'

**Comment by bknueven** [comment]
This bug is addressed by PR #59 (in found its way in during a recent re-factor pass).

For now, you can work around it by deleting the line
`--output-ruc-initial-conditions`
from `simulate_with_network_deterministic.txt`. It only affects what gets printed to the screen, not the simulation itself.

**Comment by MajidSKhoshghalb** [comment]
@bknueven Thank you.
